### ISSUE TITLE
How to add build arguments as secrets?

### ISSUE THREAD

**Issue by vishal24tuniki** [drone-plugins/drone-ecr#47] opened 2017-10-07 02:39 UTC
I have specific case where i want to pass GITHUB_OAUTH_TOKEN as build_args for creating docker image. Clearly i wouldn't want to plainly add token in .drone.yml the below way

```
publish:
    image: plugins/ecr
    ........
    ........
    build_args:
      - GITHUB_OAUTH_TOKEN=xxx

```

@tboerger @bradrydzewski can you please suggest?

**Comment by vishal24tuniki** [comment] 2017-10-07 12:25
I have also tried setting drone secret github_oauth_token=xxx and use the below yml

```
publish:
    image: plugins/ecr
    ........
    ........
    build_args:
      - GITHUB_OAUTH_TOKEN=$${GITHUB_OAUTH_TOKEN}
```

it still didn't work

**Comment by bradrydzewski** [comment] 2017-10-07 15:17
1) please search the issue tracker for existing issues https://github.com/drone-plugins/drone-ecr/issues/37
2) please do not create github issues AND discourse threads. Choose one

**Comment by bradrydzewski** [comment] 2017-10-07 15:17
closing as duplicate of https://github.com/drone-plugins/drone-ecr/issues/37

**Closed as completed by bradrydzewski** 2017-10-07 15:17 UTC
